"""empty message

Revision ID: fcf5d2c91e55
Revises: 0d9ceaac1c0c
Create Date: 2024-01-30 13:01:51.324865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf5d2c91e55'
down_revision: Union[str, None] = '0d9ceaac1c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.drop_column('sites', 'user_id')
    # ### end Alembic commands ###
